# Generated by Django 4.2.3 on 2023-07-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=10)),
                ('status_kelas', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='WaliSantri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wali', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('no_telpon', models.CharField(blank=True, max_length=200, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wali Santri',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('ttl', models.DateField()),
                ('tahun_akademik', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.kelas')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_induk', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('pendidikan', models.CharField(choices=[('UNIVERSITAS ZAINUL HASAN', 'UNIVERSITAS ZAINUL HASAN'), ('SMA Zainul Hasan', 'SMA Zainul Hasan'), ('MA Zainul Hasan', 'MA Zainul Hasan'), ('SMP Zainul Hasan', 'SMP Zainul Hasan'), ('MTS Zainul Hasan', 'MTS Zainul Hasan')], max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nama_wali', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.walisantri')),
            ],
            options={
                'verbose_name_plural': 'Santri',
            },
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengurus', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('no_telpon', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pengurus',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembayaran', models.CharField(max_length=100)),
                ('biaya', models.CharField(max_length=100)),
                ('tahun', models.CharField(max_length=100)),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.kelas')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.siswa')),
            ],
            options={
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggaran', models.CharField(blank=True, max_length=200, null=True)),
                ('kategory', models.CharField(blank=True, choices=[('Ringan', 'Ringan'), ('Sedang', 'Sedang'), ('Berat', 'Berat')], max_length=150)),
                ('kejadian', models.DateField()),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('hukuman', models.CharField(blank=True, max_length=150)),
                ('nama_santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.santri')),
            ],
            options={
                'verbose_name_plural': 'Laporan Pelanggaran',
            },
        ),
    ]
