# Generated by Django 4.2.3 on 2023-07-19 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pengurus',
            new_name='Petugas',
        ),
        migrations.AlterModelOptions(
            name='petugas',
            options={'verbose_name_plural': 'Petugas'},
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='nama_pengurus',
            new_name='nama_petugas',
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='nama_santri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.siswa'),
        ),
        migrations.DeleteModel(
            name='Santri',
        ),
        migrations.DeleteModel(
            name='WaliSantri',
        ),
    ]
