# Generated by Django 3.2 on 2023-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_auto_20230814_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anak',
            name='tanggal_operasi',
            field=models.DateField(),
        ),
    ]
