# Generated by Django 4.2.3 on 2023-07-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_rename_pengurus_petugas_alter_petugas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RincianPembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, choices=[('KMS', 'KMS'), ('LKS', 'LKS'), ('Komputer', 'Komputer')], max_length=150)),
                ('tanggal', models.DateField()),
                ('biaya', models.CharField(max_length=100)),
                ('keterangan', models.CharField(blank=True, choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=150)),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.kelas')),
                ('nama_siswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siswa.siswa')),
            ],
            options={
                'verbose_name_plural': 'Rincian Pembayaran',
            },
        ),
    ]
