# Generated by Django 4.2.3 on 2023-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_rincianpembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
