# Generated by Django 4.2.3 on 2023-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_siswa_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='status_kelas',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=8),
        ),
    ]
