# Generated by Django 4.2.3 on 2023-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_alter_kelas_status_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugas',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=8),
        ),
    ]
