# Generated by Django 4.2.3 on 2023-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0006_alter_petugas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugas',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
